# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

### BEGIN fix scp if bashrc used to source script ###
# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return;;
esac
### END fix scp if bashrc used to source script ###
# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# Source Galaxy virutalenv
source /home/galaxy/galaxy/.venv/bin/activate


#branch git script
# Show git branch name
force_color_prompt=yes
color_prompt=yes
parse_git_branch() {
 git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
if [ "$color_prompt" = yes ]; then
 PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;31m\]$(parse_git_branch)\[\033[00m\]\$ '
else
 PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w$(parse_git_branch)\$ '
fi
unset color_prompt force_color_prompt

# User specific aliases and functions
/home/galaxy/.laniakea_utils/check_instance
#help dockerCASC function $1 nome tool $2 docker name
function dockerrCASC { sudo docker run -e "GALAXY_SLOTS=$GALAXY_SLOTS" -v /home/galaxy/galaxy:/home/galaxy/galaxy:rw -v /home/galaxy/galaxy/tools/test_rCASC_wrappers/$1:/home/galaxy/galaxy/tools/rCASC_wrappers/$1:rw -v /home/galaxy/galaxy/database/tmp:/home/galaxy/galaxy/database/tmp:rw -v /export/galaxy/database/job_working_directory/$1:/export/galaxy/database/job_working_directory/$1:rw -v /export/galaxy/database/job_working_directory/$1:/export/galaxy/database/job_working_directory/$1:rw -v /export/galaxy/database/files:/export/galaxy/database/files:rw -w /export/galaxy/database/job_working_directory/$1 --net host -it -u root $2 /bin/bash;}
export -f dockerrCASC

#help function DIR $1 --> name tool
function DIR { mkdir -p /export/galaxy/database/job_working_directory/$1 ; mkdir -p /home/galaxy/galaxy/tools/test_rCASC_wrappers/$1;}
export -f DIR 

